manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      # Additional modules containing boards/shields/custom code can be listed here as well.
      # See:
      # - https://zmk.dev/docs/features/modules
      # - https://docs.zephyrproject.org/3.5.0/develop/west/manifest.html#projects
    - name: gpeye
      url-base: https://github.com/GPeye
  projects:
    - name: eyelash_sofle
      url: https://github.com/a741725193/zmk-sofle
      revision: refactor
    - name: mario-peripheral-animation
      remote: gpeye
      revision: main
    - name: zmk
      remote: zmkfirmware
      # TODO: Pin to a specific commit hash from before Zephyr 4.1 upgrade for stability
      # Steps to find the right commit:
      # 1. Go to https://github.com/zmkfirmware/zmk/commits/main
      # 2. Find a commit from around Dec 1-3, 2024 (when your builds were working)
      # 3. Copy the commit SHA (first 7-12 characters, e.g., "a1b2c3d")
      # 4. Replace "main" below with that commit hash
      # Example: revision: a1b2c3d
      revision: main
      import: app/west.yml
  self:
    path: config
