manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      # Additional modules containing boards/shields/custom code can be listed here as well.
      # See:
      # - https://zmk.dev/docs/features/modules
      # - https://docs.zephyrproject.org/3.5.0/develop/west/manifest.html#projects
    - name: gpeye
      url-base: https://github.com/GPeye
  projects:
    - name: eyelash_sofle
      url: https://github.com/a741725193/zmk-sofle
      revision: refactor
    - name: mario-peripheral-animation
      remote: gpeye
      revision: main
    - name: zmk
      remote: zmkfirmware
      # Pinned to stable version before Zephyr 4.1 upgrade to avoid breaking changes
      # If this commit doesn't work, check https://github.com/zmkfirmware/zmk/commits/main
      # and find a commit from around when your builds were last working
      revision: 3.2
      import: app/west.yml
  self:
    path: config
